@echo off
REM Flutter Build Memory Diagnostic Script
REM Generated by Eulalia Orchestrator

echo ========================================
echo Flutter Build Memory Diagnostic
echo ========================================
echo.

echo [1/5] Checking available system memory...
systeminfo | findstr /C:"Available Physical Memory" /C:"Total Physical Memory"
echo.

echo [2/5] Checking running Java/Dart processes...
tasklist | findstr /C:"java.exe" /C:"dart.exe" /C:"flutter.exe"
echo.

echo [3/5] Stopping all Gradle daemons...
cd android
call gradlew.bat --stop
cd ..
echo.

echo [4/5] Cleaning Flutter build artifacts...
call flutter clean
echo.

echo [5/5] Killing orphaned processes...
taskkill /F /IM dart.exe 2>nul
taskkill /F /IM java.exe /FI "WINDOWTITLE eq gradle*" 2>nul
echo.

echo ========================================
echo Diagnostic complete!
echo ========================================
echo.
echo Next steps:
echo 1. Close unnecessary applications
echo 2. Run: flutter run --verbose
echo 3. If still failing, try: flutter run --release
echo.
pause
